### ISSUE TITLE
some problems about ATE.rmse

### ISSUE THREAD

**Issue by gyk321** [silencht/SG-SLAM#3]
Hello,author.When I run the Example codes,I notice that the absolute_translational_error .rmse is random.Taking the fr3_walking_xyz dataset for example,sometime it rises to 0.33m,sometime it drops to 0.05m.So I'm wondering is this normal? Hoping to your reply.

**Comment by silencht** [comment]
Yes, unfortunately. This happened occasionally when I was conducting tests a long time ago. The situation you describe does occur due to a variety of issues such as some parameter settings in the program, the accuracy of the detection model (occasionally the detection results are not satisfactory for some frames), and the degradation of the  epipolar constraint. （All of the above were my guesses at the time）.

I didn't solve the problem completely. My original idea was to switch to a better detection model or add another constraint (e.g. other geometric constraints or IMU prior, etc.) for the control variables experiment. But this takes time, so it has been delayed.

**Comment by gyk321** [comment]
Thanks for your reply.By the way,when do you release your octomap configuration files? Can't wait for it

**Comment by silencht** [comment]
Are you referring to this file, please?
[octomap.launch](https://github.com/silencht/SG-SLAM/blob/main/src/octomap_server/launch/octomap.launch)

**Comment by gyk321** [comment]
Nope, I have solved my problem. Your project is excellent semantic SLAM. Well done!
